/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchRouteImport } from './routes/match'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsIndexRouteImport } from './routes/quests/index'
import { Route as QuestsIdRouteImport } from './routes/quests/$id'
import { Route as QuestActiveRouteImport } from './routes/quest.active'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIdRoute = QuestsIdRouteImport.update({
  id: '/quests/$id',
  path: '/quests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestActiveRoute = QuestActiveRouteImport.update({
  id: '/quest/active',
  path: '/quest/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/quest/active': typeof QuestActiveRoute
  '/quests/$id': typeof QuestsIdRoute
  '/quests/': typeof QuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/quest/active': typeof QuestActiveRoute
  '/quests/$id': typeof QuestsIdRoute
  '/quests': typeof QuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/quest/active': typeof QuestActiveRoute
  '/quests/$id': typeof QuestsIdRoute
  '/quests/': typeof QuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/match'
    | '/onboarding'
    | '/quest/active'
    | '/quests/$id'
    | '/quests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/match'
    | '/onboarding'
    | '/quest/active'
    | '/quests/$id'
    | '/quests'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/match'
    | '/onboarding'
    | '/quest/active'
    | '/quests/$id'
    | '/quests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  MatchRoute: typeof MatchRoute
  OnboardingRoute: typeof OnboardingRoute
  QuestActiveRoute: typeof QuestActiveRoute
  QuestsIdRoute: typeof QuestsIdRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$id': {
      id: '/quests/$id'
      path: '/quests/$id'
      fullPath: '/quests/$id'
      preLoaderRoute: typeof QuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest/active': {
      id: '/quest/active'
      path: '/quest/active'
      fullPath: '/quest/active'
      preLoaderRoute: typeof QuestActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  MatchRoute: MatchRoute,
  OnboardingRoute: OnboardingRoute,
  QuestActiveRoute: QuestActiveRoute,
  QuestsIdRoute: QuestsIdRoute,
  QuestsIndexRoute: QuestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
